/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfitRouteImport } from './routes/profit'
import { Route as MoneyRouteImport } from './routes/money'
import { Route as CapitalRouteImport } from './routes/capital'
import { Route as IndexRouteImport } from './routes/index'

const ProfitRoute = ProfitRouteImport.update({
  id: '/profit',
  path: '/profit',
  getParentRoute: () => rootRouteImport,
} as any)
const MoneyRoute = MoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => rootRouteImport,
} as any)
const CapitalRoute = CapitalRouteImport.update({
  id: '/capital',
  path: '/capital',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capital': typeof CapitalRoute
  '/money': typeof MoneyRoute
  '/profit': typeof ProfitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capital': typeof CapitalRoute
  '/money': typeof MoneyRoute
  '/profit': typeof ProfitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capital': typeof CapitalRoute
  '/money': typeof MoneyRoute
  '/profit': typeof ProfitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/capital' | '/money' | '/profit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/capital' | '/money' | '/profit'
  id: '__root__' | '/' | '/capital' | '/money' | '/profit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapitalRoute: typeof CapitalRoute
  MoneyRoute: typeof MoneyRoute
  ProfitRoute: typeof ProfitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profit': {
      id: '/profit'
      path: '/profit'
      fullPath: '/profit'
      preLoaderRoute: typeof ProfitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/money': {
      id: '/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof MoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capital': {
      id: '/capital'
      path: '/capital'
      fullPath: '/capital'
      preLoaderRoute: typeof CapitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapitalRoute: CapitalRoute,
  MoneyRoute: MoneyRoute,
  ProfitRoute: ProfitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
